########################################### Filebeat ###########################################
filebeat_version: '7.10.0'
elastic_gpg_key_url: 'https://artifacts.elastic.co/GPG-KEY-elasticsearch'
elastic_repo_url: 'deb https://artifacts.elastic.co/packages/7.x/apt stable main'
logstash_server: ["logging.hackinglab.network:55044"]
logstash_enable_tls: true
logstash_tls_verification_mode: 'none'

########################################### Osquery ###########################################
osquery_gpg_key: '1484120AC4E9F8A1A577AEEE97A80C63C9D8B80B'
osquery_repo_url: 'deb [arch=amd64] https://pkg.osquery.io/deb deb main'

########################################### Zeek ###########################################
zeek_user: 'zeek'
zeek_version: '3.2.2'
zeek_tar_url: 'https://download.zeek.org/zeek-{{ zeek_version }}.tar.gz'
zeek_dir: '/opt/zeek'
zeek_build_dir: '/tmp/zeek'
zkg_version: '2.4.2'

############################################## PF_RING ##############################################
pfring_dir: '/opt/pf_ring'
pfring_version: '7.6.0'
pfring_tar_url: 'https://github.com/ntop/PF_RING/archive/{{ pfring_version }}.tar.gz'

############################################## Suricata ##############################################
suricata_dir: '/tmp/suricata'
suricata_version: '5.0.3'
suricata_tar_url: 'https://www.openinfosecfoundation.org/download/suricata-{{ suricata_version }}.tar.gz'

suricata_username: 'suricata'

suricata_configure_prefix: '/usr'
suricata_configure_sysconfdir: '/etc'
suricata_configure_localstatedir: '/var'
suricata_configure_libpfring_includes: '/usr/local/include'
suricata_configure_libpfring_libraries: '/usr/local/lib'
suricata_configure: 'LIBS="-lrt" ./configure --prefix={{ suricata_configure_prefix }} --sysconfdir={{ suricata_configure_sysconfdir }} --localstatedir={{ suricata_configure_localstatedir }} --enable-pfring --with-libpfring-includes={{ suricata_configure_libpfring_includes }} --with-libpfring-libraries={{ suricata_configure_libpfring_libraries }}'
