##############################################################
# Install Docker
##############################################################
- name: Uninstall old versions
  apt:
    name: ['docker', 'docker-engine', 'docker.io', 'containerd', 'runc']
    state: absent
  
- name: Add Docker GPG key
  apt_key:
    url: "{{ docker_gpg_key_url }}"
    state: present

- name: Add Docker repository into sources list
  apt_repository:
    repo: "{{ docker_repo_url }}"
    state: present

- name: Install Docker
  apt: 
    name: ['apt-transport-https', 'ca-certificates', 'curl', 'gnupg-agent', 'software-properties-common', 'docker-ce', 'docker-ce-cli','containerd.io']
    state: latest

- name: Enable Docker service
  service:
    name: 'docker'
    enabled: yes
    state: started