##############################################################
# Install Filebeat
##############################################################
- name: Add Elastic GPG key
  apt_key:
    url: "{{ elastic_gpg_key_url }}"
    state: present

- name: Add Elastic repository into sources list
  apt_repository:
    repo: "{{ elastic_repo_url }}"
    state: present

- name: Install Filebeat
  apt:
    name: 'filebeat={{ filebeat_version }}'
    state: present

##############################################################
# Config Filebeat
##############################################################
- name: Copy server CA
  copy:
    src: '{{ item }}'
    dest: '/etc/ssl/certs/logstash_server_pki_int.crt'
    owner: 'root'
    group: 'root'
    mode: 0644
  with_fileglob:
    - 'conf/tls/root_ca/*.crt'
  when: client_cert == True

- name: Copy Filebeat client public cert
  copy:
    src: '{{ item }}'
    dest: '/etc/ssl/certs/tor_client.crt'
    owner: 'root'
    group: 'root'
    mode: 0644
  with_fileglob:
    - 'conf/tls/client_cert/*.crt'
  when: client_cert == True  

- name: Copy Filebeat client private key
  copy:
    src: '{{ item }}'
    dest: '/etc/ssl/private/tor_client.key'
    owner: 'root'
    group: 'root'
    mode: 0400
  with_fileglob:
    - 'conf/tls/client_cert/*.key'
  when: client_cert == True  

- name: Copy filebeat.yml
  template:
    src: 'conf/filebeat/filebeat.yml'
    dest: '/etc/filebeat/filebeat.yml'
    owner: 'root'
    group: 'root'
    mode: 0600

- name: Verify Filebeat connection to Logstash
  shell: 'filebeat test output'
  register: filebeat_tls_check

- name: Print result of Filebeat TLS check
  debug:
    msg: '{{ filebeat_tls_check.stdout_lines }}'

- name: Restart Filebeat
  service:
    name: 'filebeat'
    enabled: yes
    state: restarted